services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend  # Nom du conteneur
    ports:
      - "8080:8050"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports: 
      - "8081:8051"
    depends_on:
      - backend
    restart: always